config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home', :constraints => UserRequiredConstraint.new
  root to: 'pages#landing', :constraints => NoUserRequiredConstraint.new, as: nil

  resources :users, except: [:show, :edit, :index] do
    member do
      get :activate
    end
  end

  get '/privacy_policy', to: 'pages#privacy_policy', as: :privacy_policy
  get '/imprint', to: 'pages#imprint', as: :imprint

  resources :user_sessions, only: [:create]
  resources :recipes
  resources :meal_plans
  resources :beta_candidates, only: %i[create] do
    collection do
      get :confirm
    end
  end
  post 'swap_recipe/:id', to: 'meal_plans#swap_recipe', as: :meal_plan_swap_recipe
  post 'update_with_shopping_list/:id', to: 'meal_plans#update_with_shopping_list', as: :meal_plan_with_shopping_list
  post 'toggle_checked_off/:id', to: 'shopping_lists#toggle_ingredient_checked_off', as: :shopping_list_toggle_checked_off

  # Profile aliases
  get 'login', to: 'user_sessions#new', as: :login
  post 'logout', to: 'user_sessions#destroy', as: :logout
  get 'edit_profile', to: 'users#edit', as: :edit_profile
  get 'export_to_things/:id', to: 'meal_plans#share_to_things', as: :export_to_things
end

app/models/meal_plan.rb
class MealPlan < ApplicationRecord
  belongs_to :user
  has_one :shopping_list
  has_and_belongs_to_many :recipes

  scope :most_recent, -> { order('created_at DESC').first }
  scope :committed, -> { where(committed: true) }
  scope :uncommitted, -> { where(committed: false) }

  def recipes_changable?
    enough_recipes? && !shopping_list.present?
  end

  def enough_recipes?
    user.recipes.count > recipes.count
  end
end

app/controllers/meal_plans_controller.rb
class MealPlansController < ApplicationController
  def new
    if current_user.meal_plans.uncommitted.any?
      flash[:notice] = "You have an uncommitted meal plan lying around"
      redirect_to meal_plan_path(current_user.meal_plans.uncommitted.first)
    else
      @meal_plan = MealPlan.new(number_of_meals: 2)
    end
  end

  def index
    @meal_plans = current_user.meal_plans.order(created_at: :desc)
  end

  def create
    # TODO: Move guard claused to pundit
    needed_recipes = meal_plan_params[:number_of_meals]
    redirect_to recipes_path and return if current_user.recipes.none?
    redirect_to recipes_path and return if needed_recipes.to_i > current_user.recipes.count

    result = CommitMealPlan.call(params: meal_plan_params, proposal: params[:proposal].present?, user: current_user)
    if result.success?
      @meal_plan = result.meal_plan
      @shopping_list = result.shopping_list
      redirect_to meal_plan_path(@meal_plan)
    else
      flash[:notice] = "Something went wrong"
      render :new
    end
  end

  def update_with_shopping_list
    @meal_plan = MealPlan.find(params[:id])
    @shopping_list = ShoppingList.build_from_meal_plan(@meal_plan, current_user)

    if @shopping_list.save
      @meal_plan.update(committed: true)
      redirect_to meal_plan_path(@meal_plan)
    else
      # TODO: Pass error message
      redirect_to meal_plan_path(@meal_plan)
    end
  end

  def swap_recipe
    @meal_plan = MealPlan.find(params[:id])
    raise ActionController::RoutingError.new('Not Found') unless meal_plan_accessible?
    return unless @meal_plan.recipes_changable?

    recipe_ids = @meal_plan.recipe_ids

    new_recipe_id = Recipe.where.not(id: recipe_ids).order("RANDOM()").first.id

    recipe_ids.delete(params[:recipe_id].to_i)
    recipe_ids.push(new_recipe_id)

    if @meal_plan.update(recipe_ids: recipe_ids)
      redirect_to meal_plan_path(@meal_plan), notice: 'Changed recipe'
    else
      flash.now[:alert] = 'Login failed'
      render :show
    end
  end

  def show
    @meal_plan = current_user.meal_plans.find(params[:id])
    if @meal_plan.shopping_list.present?
      @shopping_list_ingredients = @meal_plan.shopping_list.shopping_list_ingredients.checked_off_last
    end
  end

  def share_to_things
    meal_plan = current_user.meal_plans.find(params[:id])
    date = meal_plan.created_at.strftime("%d.%m.%Y")
    render json: ThingsJsonService.new(meal_plan.shopping_list, date).build_link
  end

  private

  def meal_plan_accessible?
    @meal_plan.user == current_user
  end

  def meal_plan_params
    params.require(:meal_plan).permit(:number_of_meals)
  end
end

app/views/meal_plans/_form.html.erb
<%= form_with(model: meal_plan, local: true) do |form| %>
  <% if local_assigns[:proposal] %>
    <%= hidden_field_tag(:proposal, value: true) %>
  <% end %>
  
  <% if meal_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meal_plan.errors.count, "error") %> prohibited this meal plan from being saved:</h2>

      <ul>
        <% meal_plan.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field mb-6">
    <%= form.label :number_of_meals, class: 'block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2' %>
    <%= form.number_field :number_of_meals, class: 'appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500' %>
  </div>

  <div class="actions">
    <%= form.submit "Create meal plan", class: 'Button'  %>
  </div>
<% end %>

app/views/meal_plans/index.html.erb
<h1 class="text-3xl mb-4 mt-8">Meal Plans</h1>
<% if @meal_plans.any? %>
  <% @meal_plans.each_with_index do |meal_plan, index| %>
    <% if index == 0 %>
      <h2 class="text-xl mb-2 mt-4">Most recent</h2>
    <% end %>
    <div class="mb-4 Card">
      <div class="mb-2">
        <h3>Meal plan from <%= meal_plan.created_at.strftime("%d %b, %Y at %H:%M") %></h3>
        <p><%= meal_plan.recipes.count %> Recipes</p>
      </div>
      <%= link_to "Show", meal_plan_path(meal_plan), class: "TextButton" %>
    </div>
    <% if index == 0 %>
      <div class="mb-16"></div>
      <h2 class="text-xl mb-2 mt-4">Archived</h2>
    <% end %>
  <% end %>
<% else %>
  <p>No meal plans yet</p>
<% end %>

app/views/meal_plans/new.html.erb
<div class="max-w-xl rounded overflow-hidden shadow-lg rounded-md bg-white sm:mt-8 md:mt-16 mx-auto p-4 mb-16">
  <h1 class="text-xl font-extrabold mb-4">New Meal Plan</h1>
  <%= render 'form', meal_plan: @meal_plan, proposal: true %>
</div>

app/views/meal_plans/show.html.erb
<div class="mt-8 mb-8">
  <h1 class="PageHeadline">Meal Plan (<%= @meal_plan.recipes.count %> Meals)</h1>
  <small>Created at <%= @meal_plan.created_at.strftime("%d %b, %Y at %H:%M") %></small>
</div>
<div class="flex flex-wrap">
  <% @meal_plan.recipes.each do |recipe| %>
    <div class="Card mb-8 md:flex-1 mr-4 w-full">
      <h2 class="CardHeadline mb-4"><%= recipe.name %></h2>
      <% if recipe.description.present? %>
        <p class="mb-4"><%= recipe.description %></p>
      <% end %>
      <% if @meal_plan.recipes_changable? %>
        <%= link_to 'Swap out recipe', meal_plan_swap_recipe_path(@meal_plan.id, recipe_id: recipe.id), method: :post, class: 'SecondaryButton' %>
      <% end %>
    </div>
  <% end %>
</div>

<% if !@meal_plan.recipes_changable? && !@meal_plan.enough_recipes? && !@meal_plan.committed? %>
  <div class="text-center">
    <p>Recipes are not changable since you do not have enought recipes in your database</p>
    <%= link_to 'Add more', new_recipe_path, class: 'TextButton mt-2 inline-block' %>
  </div>
<% end %>

<% if !@meal_plan.committed? %>
  <%= link_to 'Commit', meal_plan_with_shopping_list_path(@meal_plan.id), method: :post, class: 'SecondaryButton' %>
<% end %>

<% if @meal_plan.committed? %>
  <div class="mt-8" data-controller="shopping-list-item">
    <h2 class="SecondaryHeadline ">Shopping List</h2>
    <table class="table-auto">
      <thead>
        <tr>
          <th class="px-4 py-2">Checked off?</th>
          <th class="px-4 py-2">Item</th>
          <th class="px-4 py-2">Amount</th>
        </tr>
      </thead>
      <tbody data-target="shopping-list-item.itemList">
        <% @shopping_list_ingredients.each do |ingredient| %>
          <tr class="bg-white even:bg-gray-300" data-action="click->shopping-list-item#toggle" data-id="<%= ingredient.id %>">
            <td class="border px-4 py2">
              <input style="pointer-events: none" <%= ingredient.checked_off? ? 'checked' : nil %> type="checkbox"   />
            </td>
            <td class="border px-4 py2">
              <%= ingredient.ingredient_name %>
            </td>
            <td class="border px-4 py2">
              <% ingredient.amount.map do |amount| %>
                <%= amount %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="mt-4" data-controller="shopping-list-sharing">
    <button class="px-2 py-2 back bg-indigo-500 text-white rounded" data-meal-plan-id="<%= @meal_plan.id %>" data-action="shopping-list-sharing#things">Share to things</button>
  </div>
<% end %>