config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home', :constraints => UserRequiredConstraint.new
  root to: 'pages#landing', :constraints => NoUserRequiredConstraint.new, as: nil

  resources :users, except: [:show, :edit, :index] do
    member do
      get :activate
    end
  end

  get '/privacy_policy', to: 'pages#privacy_policy', as: :privacy_policy
  get '/imprint', to: 'pages#imprint', as: :imprint

  resources :user_sessions, only: [:create]
  resources :recipes
  resources :meal_plans
  resources :beta_candidates, only: %i[create] do
    collection do
      get :confirm
    end
  end
  post 'swap_recipe/:id', to: 'meal_plans#swap_recipe', as: :meal_plan_swap_recipe
  post 'update_with_shopping_list/:id', to: 'meal_plans#update_with_shopping_list', as: :meal_plan_with_shopping_list
  post 'toggle_checked_off/:id', to: 'shopping_lists#toggle_ingredient_checked_off', as: :shopping_list_toggle_checked_off

  # Profile aliases
  get 'login', to: 'user_sessions#new', as: :login
  post 'logout', to: 'user_sessions#destroy', as: :logout
  get 'edit_profile', to: 'users#edit', as: :edit_profile
  get 'export_to_things/:id', to: 'meal_plans#share_to_things', as: :export_to_things
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients
  has_and_belongs_to_many :meal_plans
  accepts_nested_attributes_for :recipe_ingredients, allow_destroy: true

  validates_presence_of :name

  scope :ordered_random, -> { order("RANDOM()") }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = current_user.recipes
  end

  def new
    @recipe = Recipe.new
    @recipe.recipe_ingredients.build.build_ingredient
  end

  def show
    @recipe = current_user.recipes.find(params[:id])
    raise ActionController::RoutingError.new('Not Found') unless recipe_accessible?
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe created'
    else
      render :new
    end
  end

  def edit
    @recipe = current_user.recipes.find(params[:id])
  end

  def update
    @recipe = current_user.recipes.find(params[:id])
    if @recipe.update(recipe_params)
      if recipe_in_active_meal_plan(@recipe.id)
        current_meal_plan.shopping_list.regenerate_ingredients!
      end
      redirect_to recipe_path(@recipe), notice: 'Recipe updated'
    else
      render :edit
    end
  end

  def destroy
    @recipe = current_user.recipes.find(params[:id])
    if @recipe.destroy
      redirect_to recipes_path, notice: 'Recipe deleted'
    else
      render :show
    end
  end

  private

  def current_meal_plan
    @current_meal_plan ||= current_user.meal_plans.most_recent
  end

  def recipe_in_active_meal_plan(recipe_id)
    return false unless current_meal_plan.present?

    active_recipes = current_meal_plan.recipes.pluck(:id)
    active_recipes.include?(recipe_id)
  end

  def recipe_params
    params.require(:recipe).permit(:name, :description, :recipe_ingredients_attributes => [:id, :amount, :unit, :_destroy, :ingredient_attributes => [:name]])
  end

  def recipe_accessible?
    @recipe.user == current_user
  end
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field mb-6">
    <%= form.label :name, class: 'block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2' %>
    <%= form.text_field :name, class: 'appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500' %>
  </div>

  <div class="field mb-6">
    <%= form.label :description, class: 'block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2' %>
    <%= form.text_area :description, class: 'appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500' %>
  </div>
  <h3 class="font-bold mb-3 text-gray-700">Ingredients</h3>
  <div class="field mb-6" data-controller="recipe-rows saved-recipe-row">
    <div data-target="recipe-rows.container">
      <%= form.fields_for :recipe_ingredients do |ingredients_form| %>
        <%= ingredients_form.fields_for :ingredient do |ingredient_form| %>
          <div class=" flex flex-row" data-target="recipe-rows.row">
            <div class="field mb-6 mr-3">
              <%= ingredient_form.label :name, class: 'block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2' %>
              <%= ingredient_form.text_field :name, class: 'appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500' %>
            </div>
            <div class="field mb-6 mr-3">
              <%= ingredients_form.label :amount, class: 'block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2' %>
              <%= ingredients_form.text_field :amount, class: 'appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500' %>
            </div>
            <div class="field mb-6 mr-3">
              <%= ingredients_form.label :unit, class: 'block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2' %>
              <%= ingredients_form.select :unit, options_for_select(RecipeIngredient::ALLOWED_UNITS), {}, { class: "appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500" } %>
            </div>
            <%= ingredients_form.hidden_field :_destroy %>
            <div data-action="click->saved-recipe-row#markForDelete" class="cursor-pointer self-center bg-red-300 hover:bg-red-400 text-gray-800 py-2 px-4 rounded">Remove</div>
          </div>
        <% end %>
      <% end %>
    </div>
    <a href="#" data-action="recipe-rows#addRow" class="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded">+ Add row</a>
  </div>

  <div class="actions mt-12">
    <% button_text = recipe.persisted? ? "Update recipe" : "Create recipe" %>
    <%= form.submit button_text, class: 'Button'  %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<div class="max-w-xl rounded overflow-hidden shadow-lg rounded-md bg-white sm:mt-8 md:mt-16 mx-auto p-4 mb-16">
  <h1 class="text-xl font-extrabold mb-4">Edit recipe</h1>
  <%= render 'form', recipe: @recipe %>
</div>

app/views/recipes/index.html.erb
<div class="flex justify-between mt-4 mb-2 md:mt-8 md:mb-4">
  <h1 class="PageHeadline">Your recipes</h1>
  <%= link_to 'Add new', new_recipe_path, class: 'Button mb-4' %>
</div>
<% if @recipes.present? %>
  <% @recipes.each do |recipe| %>
    <div class="mb-4">
      <h2 class="SecondaryHeadline text-teal-500">
        <%= link_to recipe.name, recipe_path(recipe) %>
      </h2>
      <p class="text-gray-600"><%= recipe.description %></p>
      <small><%= recipe.created_at.strftime("%d %b, %Y at %H:%M") %></small>
    </div>
  <% end %>
<% else %>
  <p>No recipes yet</p>
<% end %>

app/views/recipes/new.html.erb
<div class="max-w-xl rounded overflow-hidden shadow-lg rounded-md bg-white sm:mt-8 md:mt-16 mx-auto p-4 mb-16">
  <h1 class="text-xl font-extrabold mb-4">New Recipe</h1>
  <%= render 'form', recipe: @recipe %>
</div>

app/views/recipes/show.html.erb
<div class="grid grid-cols-2 gap-4">
  <div>
    <h1 class="PageHeadline mt-4 mb-2"><%= @recipe.name %></h1>
    <p><%= @recipe.description %></p>
  </div>
  <div class="self-center">
    <%= link_to 'Edit', edit_recipe_path(@recipe), class: 'bg-purple-500 hover:bg-purple-700 text-white font-bold py-2 px-4 rounded block w-full md:inline-block md:w-auto' %>
    <%= link_to 'Delete', recipe_path(@recipe), method: :delete, data: {confirm: "Are you sure?"},  class: 'bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded block w-full md:inline-block md:w-auto' %>
  </div>
</div>


<h2 class="SecondaryHeadline mt-8 mb-2">Ingredients</h2>
<table class="table-auto">
  <thead>
    <tr>
      <th class="px-4 py-2">Ingredient</th>
      <th class="px-4 py-2">Amount</th>
    </tr>
  </thead>
  <tbody>
    <% @recipe.recipe_ingredients.each do |ingr| %>
      <tr class="odd:bg-gray-200">
        <td class="border px-4 py-2">
          <p><%= ingr.ingredient_name %></p>
        </td>
        <td class="border px-4 py-2">
          <p><%= ingr.amount %> <%= ingr.unit %></p>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>