config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home', :constraints => UserRequiredConstraint.new
  root to: 'pages#landing', :constraints => NoUserRequiredConstraint.new, as: nil

  resources :users, except: [:show, :edit, :index] do
    member do
      get :activate
    end
  end

  get '/privacy_policy', to: 'pages#privacy_policy', as: :privacy_policy
  get '/imprint', to: 'pages#imprint', as: :imprint

  resources :user_sessions, only: [:create]
  resources :recipes
  resources :meal_plans
  resources :beta_candidates, only: %i[create] do
    collection do
      get :confirm
    end
  end
  post 'swap_recipe/:id', to: 'meal_plans#swap_recipe', as: :meal_plan_swap_recipe
  post 'update_with_shopping_list/:id', to: 'meal_plans#update_with_shopping_list', as: :meal_plan_with_shopping_list
  post 'toggle_checked_off/:id', to: 'shopping_lists#toggle_ingredient_checked_off', as: :shopping_list_toggle_checked_off

  # Profile aliases
  get 'login', to: 'user_sessions#new', as: :login
  post 'logout', to: 'user_sessions#destroy', as: :logout
  get 'edit_profile', to: 'users#edit', as: :edit_profile
  get 'export_to_things/:id', to: 'meal_plans#share_to_things', as: :export_to_things
end

app/views/pages/_meal_plan.html.erb
<% dummy_emojis = %w[🍟 🍲 🍔 🍝 🧆 🌱 🌯] %>
<% dummy_emojis_filtered = dummy_emojis.sample(meal_plan.recipes.count) %>

<div class="Card MealPlanCard">
  <div class="flex flex-col lg:flex-row justify-between h-full">
    <div class="flex flex-1 flex-col MealPlanCard__section-with-border pb-6 lg:pb-0">
      <div>
        <%= link_to meal_plan_path(meal_plan) do %>
          <h3 class="CardTitle">Meal plan from <%= meal_plan.created_at.strftime("%B %d") %></h3>
        <% end %>
        <small class="MealPlanCard__created-at">created on <%= meal_plan.created_at.strftime("%B %d, %Y") %></small>
      </div>
      <div class="mt-6 lg:mt-auto">
        <h4 class="MealPlanCard__meal-count"><%= meal_plan.recipes.count %> Meals</h4>
        <div class="MealPlanCard__divider"></div>
        <p class="MealPlanCard__emojis"><%= dummy_emojis_filtered.join(" ") %></p>
      </div>
    </div>
    <div class="flex flex-1 flex-col justify-between mt-6 lg:ml-6 lg:mt-0">
      <% meal_plan.recipes.each_with_index do |recipe, index| %>
        <h5 class="RecipeTitle">
          <span class="RecipeTitle__emoji"><%= dummy_emojis_filtered[index] %></span>
          <span class="RecipeTitle__name"><%= recipe.name %></span>
        </h5>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/_meal_plan_empty.html.erb
  <div class="Card">
    <div class="flex flex-col items-center py-8">
      <span class="text-3xl mb-4">😮</span>
      <span class="text-lg mb-4">You did not create any mealplans yet...</span>
      <%= link_to "Create your first mealplan", new_meal_plan_path, class: "Button" %>
    </div>
  </div>

app/views/pages/_recipe.html.erb
<% dummy_emojis = %w[🍟 🍲 🍔 🍝 🧆 🌱 🌯] %>

<div class="Card RecipeCard">
  <%= link_to recipe_path(recipe) do %>
    <h3 class="CardTitle RecipeCard__title"><%= dummy_emojis.sample %> <%= recipe.name %></h3>
  <% end%>
  <ul>
    <% recipe.recipe_ingredients.limit(4).map do |ingredient| %>
      <li class="RecipeCard__ingredient">
        <span><%= ingredient.name %></span> <span class="RecipeCard__ingredient--amount"><%= ingredient.amount %> <%= ingredient.unit %></span>
      </li>
    <% end %>
    <% if recipe.recipe_ingredients.count > 4 %>
      <li class="MoreText">+ <%= recipe.recipe_ingredients.count - 4 %> more</li>
    <% end %>
  </ul>
</div>

app/views/pages/_shopping_list.html.erb
<div class="Card">
  <h3 class="CardTitle mb-6">🛍  Grocery List</h3>
  <ul>
    <% shopping_list.shopping_list_ingredients.limit(4).each do |item| %>
      <li class="FauxCheckbox mb-6"><%= item.name %></li>
    <% end %>
    <% if shopping_list.shopping_list_ingredients.count > 4 %>
      <li class="MoreText">+ <%= shopping_list.shopping_list_ingredients.count - 4 %> more</li>
    <% end %>
  </ul>
</div>

app/views/pages/home.html.erb
<% if current_user.recipes.none? && current_user.meal_plans.none? %>
  <div class="flex flex-col items-center mt-16">
    <%= image_tag 'empty.svg', class: "w-64 mb-8" %>
    <h3 class="text-2xl font-bold">Not a lot to see here...</h3>
    <p class="mb-4">Why don't you start by adding a few recipes?</p>
    <%= link_to 'Create new recipe', new_recipe_path, class: "Button" %>
  </div>
<% end %>

<% if current_user.recipes.any? %>
  <% if current_user.meal_plans.committed.none? %>
    <div class="mb-16">
      <h2 class="Headline--card-list mb-4">Current Meal Plan</h2>
      <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div class="col-span-1 lg:col-span-2">
          <%= render "meal_plan_empty" %>
        </div>
      </div>
    </div>
  <% else %>
    <div class="mb-16">
      <h2 class="Headline--card-list mb-4">Current Meal Plan</h2>
      <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div class="col-span-1 lg:col-span-2">
          <%= render "meal_plan", meal_plan: current_user.current_meal_plan %>
        </div>
        <div class="col-span-1">
          <%= render "shopping_list", shopping_list: @shopping_list %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="flex flex-row justify-between content-center mb-4">
    <h2 class="Headline--card-list">Your recipes</h2>
    <%= link_to "See all →", recipes_path, class: "TextButton self-center" %>
  </div>
  <div class="grid gird-cols-1 lg:grid-cols-3 gap-6">
    <% @recipes.map do |recipe| %>
      <div class="col-span-1">
        <%= render 'recipe', recipe: recipe %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/pages/imprint.html.erb
<h1>Impressum</h1>

<h2>Angaben gemßäß 5 TMG</h2>
<p>Christian Poplawski<br />
Fellmühlenweg 1A<br />
51069 Köln</p>

<h2>Kontakt</h2>
<p>E-Mail: legal@dishbot.app</p>

<p>Quelle: <a href="https://www.e-recht24.de/impressum-generator.html">https://www.e-recht24.de/impressum-generator.html</a></p>

app/views/pages/landing.html.erb
<section class="LandingHeader mt-16 mb-24">
  <div class="grid grid-cols-12 col-gap-16">
    <div class="col-span-3 lg:col-span-7 mt-16 mb-16">
      <h1 class="LandingHeader__headline mt-12">Never worry about what to cook today again</h1>
      <p class="LandingHeader__claim mt-6 font-serif">Dishbot helps you <span class="LandingHeader__claim-highlight">plan your meals</span> for the next days and <span class="LandingHeader__claim-highlight">creates a shopping list</span> for you, so you can focus on enjoying delicious food.</p>
      <div class="LandingpageCta Card h-auto mt-20">
        <h3 class="LandingpageCta__cta text-2xl font-bold mb-2">⚡️ Interested? Leave us your email!</h2>
        <span class="LandingpageCta__explanation text-lg font-serif">Dishbot is currently in beta and invite-only. We’ll notify you once a new batch of codes is sent out</span>
        <%= form_for @beta_candidate, url: beta_candidates_path, method: :post do |f| %>
          <div class="flex flex-col md:flex-row flex-1 max-w-2xl mt-6">
            <%= f.text_field :email, class: "appearance-none text-gray-700 md:rounded-r-none border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500 flex-1", type: 'email', placeholder: 'example@mail.com' %>
            <%= f.submit 'Invite me', class: "Button px-6 mt-6 md:mt-0 md:rounded-l-none" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="hidden lg:block col-span-5">
      <div class="rounded-image"></div>
    </div>
  </div>
</section>

<section class="relative mt-32 mb-32">
  <div class="flex justify-center mb-16">
    <h2 class="font-bold text-center text-3xl">How it works</h2>
  </div>
  <div class="grid grid-cols-12 col-gap-12">
    <div class="col-span-12 md:col-span-5">
      <%= image_tag "landing-page.png", class: "floating-shadow" %>
    </div>
    <div class="col-span-12 md:col-span-7">
      <div class="HeadlinesList mb-12">
        <h3 class="text-xl font-bold mb-2">1. 🍳 Save your favourite recipes</h3>
        <p class="HeadlinesList__text font–l font-serif">Just the essentials: The name and ingredients, no detailed steps
    on preperation needed.</p>
      </div>
      <div class="HeadlinesList mb-12">
        <h3 class="text-xl font-bold mb-2">2. 📝 Let dishbot create a meal plan for you</h3>
        <p class="HeadlinesList__text font–l font-serif">Just tell us how many meals you want to go shopping for. We will generate
    a plan for you, you switch out the meals you don’t like.</p>
      </div>
      <div class="HeadlinesList">
        <h3 class="text-xl font-bold mb-2">3. 🛒 Buy what you need with the generated shopping list</h3>
        <p class="HeadlinesList__text font–l font-serif">Dishbot will create a shopping list for you with all the things you need to buy.
    Use it on the website or export it to your favourite ToDo-App.</p>
      </div>
    </div>
  </div>
</section>