config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home', :constraints => UserRequiredConstraint.new
  root to: 'pages#landing', :constraints => NoUserRequiredConstraint.new, as: nil

  resources :users, except: [:show, :edit, :index] do
    member do
      get :activate
    end
  end

  get '/privacy_policy', to: 'pages#privacy_policy', as: :privacy_policy
  get '/imprint', to: 'pages#imprint', as: :imprint

  resources :user_sessions, only: [:create]
  resources :recipes
  resources :meal_plans
  resources :beta_candidates, only: %i[create] do
    collection do
      get :confirm
    end
  end
  post 'swap_recipe/:id', to: 'meal_plans#swap_recipe', as: :meal_plan_swap_recipe
  post 'update_with_shopping_list/:id', to: 'meal_plans#update_with_shopping_list', as: :meal_plan_with_shopping_list
  post 'toggle_checked_off/:id', to: 'shopping_lists#toggle_ingredient_checked_off', as: :shopping_list_toggle_checked_off

  # Profile aliases
  get 'login', to: 'user_sessions#new', as: :login
  post 'logout', to: 'user_sessions#destroy', as: :logout
  get 'edit_profile', to: 'users#edit', as: :edit_profile
  get 'export_to_things/:id', to: 'meal_plans#share_to_things', as: :export_to_things
end

app/views/layouts/_footer.html.erb
<footer class="bg-gray-800 px-4 py-8 mt-16 text-gray-100">
  <div class="container mx-auto flex flex-col md:flex-row justify-between text-center md:text-left">
    <div class="mb-8 md:mb-0">
      <span>© <%= DateTime.now.strftime("%Y") %> dishbot. beep boop.</span>
    </div>
    <div>
      <%= link_to "Privacy Policy", privacy_policy_path, class: "font-medium mr-6" %>
      <%= link_to "Imprint", imprint_path, class: "font-medium" %>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div data-controller="mobile-menu" class="header">
  <div class="flex justify-between">
    <div class="">
      <%= link_to root_path, class: 'font-extrabold', class: 'header__logo-link'  do %>
        <%= image_tag 'logo.svg', class: 'header__logo-image'%>
      <% end %>
    </div>
    <nav class="hidden md:block">
      <%= render 'layouts/navigation' %>
    </nav>
    <div data-action="click->mobile-menu#toggleMenu" data-target="mobile-menu.menuButton" class="md:hidden">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" />
      </svg>
    </div>
  </div>
  <nav data-target="mobile-menu.menu" class="hidden md:hidden bg-white mt-4">
    <%= render 'layouts/navigation' %>
  </nav>
</div>

app/views/layouts/_navigation.html.erb
<div class="block navigation mt-4">
  <% if current_user %>
    <%= link_to "Recipes", recipes_path, class: 'md:inline block navigation__item' %>
    <%= link_to "Create Meal Plan", new_meal_plan_path, class: 'md:inline block navigation__item' %>
    <%= link_to "Meal Plans", meal_plans_path, class: 'md:inline block navigation__item' %>
    <%= link_to "Logout", :logout, method: :post, class: 'md:inline block  navigation__item' %>
  <% else %>
    <%= link_to "Register", new_user_path, class: 'md:inline block navigation__item' %>
    <%= link_to "Login", login_path, class: 'md:inline inline-block navigation__item navigation__item--highlight' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if Rails.env.production? %>
      <script id="Cookiebot" src="https://consent.cookiebot.com/uc.js" data-cbid="<%= ENV['COOKIEBOT_TOKEN'] %>" data-blockingmode="auto" type="text/javascript"></script>
    <% end %>
    <title>Dishbot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Sarabun:wght@400;600;700&display=swap" rel="stylesheet"> 
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@400;700&display=swap" rel="stylesheet">  
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= favicon_link_tag 'favicon.png' %>

    <% if Rails.env.production? %>
      <!-- Global site tag (gtag.js) - Google Analytics -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-C5KZ86EY4B"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', <%= ENV["G_TAG"] %>, { 'anonymize_ip': true });
      </script>
    <% end %>
  </head>

  <body class="bg-gray-100">
    <%= render 'layouts/header' %>
    <div class="fixed ml-6 mt-6">
      <% if flash[:notice] %>
        <div data-controller="flash" data-target="flash.flash" class="shadow-lg mx-auto p-4 bg-blue-500 mb-3 text-white text-style-bold rounded" id="notice"><%= flash[:notice] %></div>
      <% end %>
      <% if flash[:alert] %>
        <div data-controller="flash" data-target="flash.flash" class="shadow-lg mx-auto p-4 bg-red-500 text-white text-style-bold rounded" id="alert"><%= flash[:alert] %></div>
      <% end %>
    </div>
    <div class="container mx-auto p-4">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>